#!/usr/bin/env python3
"""認証実装確認処理 — 処理分解カタログ（データ定義）

SSOT: doc/api-platform/basic-design/research/process-design-template.md
本ファイルを更新したら上記 md の処理カタログ表も同時に更新すること。

系統（処理 ID の接頭辞）:
  巡回 … 対象検索 Lambda が 1 時間毎に回す処理
  全量 … 全量確認のときだけ動く処理（起動・全件取得・アプリ単位への割り振り）
  確認 … 1 アプリを検査する処理（巡回起点／全量起点のどちらでも同じ）
  通知 … アラート検知 Lambda / CloudWatch による通知
  運用 … 人手・異常系（メタ監視・DLQ・手動更新）
  連携 … アプリ（ベンダー）側の接点
"""

GROUPS = {
    "巡回": ("巡回・対象検索", "FFD966"),
    "全量": ("全量確認", "9DC3E6"),
    "確認": ("認証実装確認（1 アプリ）", "C6E0B4"),
    "通知": ("アラート通知", "F4B183"),
    "運用": ("運用・異常系", "C9C9C9"),
    "連携": ("アプリ接点", "D9B3E6"),
}


def P(pid, sheet, name, trigger, src, dst, mode, actor, freq, summary, perm, seq, hint):
    return dict(id=pid, sheet=sheet, name=name, group=pid.split("-")[0], trigger=trigger,
                src=src, dst=dst, mode=mode, actor=actor, freq=freq, summary=summary,
                perm=perm, seq=seq, hint=hint)


PROCESSES = [
    # ---------------- 巡回・対象検索（対象検索 Lambda）
    P("巡回-01", "認証実装確認処理開始", "認証実装確認処理開始", "巡回（1 時間毎）",
      "EventBridge Scheduler（rate(1 hour)）", "対象検索 Lambda", "非同期", "EventBridge Scheduler", "1 時間毎",
      "監視対象の変更有無を確認する巡回処理を定期起動する。",
      "Scheduler 実行ロール / lambda:InvokeFunction / lambda.{region}.amazonaws.com",
      "EventBridge Scheduler -> 対象検索 Lambda : Invoke（payload なし）",
      "リトライポリシー・Scheduler 側 DLQ の設定値を明記する（WBS A6-d）"),
    P("巡回-02", "対象アカウント一覧取得", "対象アカウント一覧取得", "巡回（1 時間毎）",
      "対象検索 Lambda", "AWS Organizations", "同期", "対象検索 Lambda", "巡回ごとに 1 回",
      "巡回対象となる App アカウントの一覧を取得する。",
      "organizations:ListAccounts（委任ポリシー方式が推奨。M-Q-17-2）/ organizations.us-east-1.amazonaws.com",
      "対象検索 Lambda -> Organizations : ListAccounts\nOrganizations --> 対象検索 Lambda : アカウント一覧",
      "列挙方式（委任 / AssumeRole / 静的リスト）と対象範囲（全体 / OU）を確定する"),
    P("巡回-03", "対象アカウント接続権限取得", "対象アカウント接続権限取得", "巡回（1 時間毎）",
      "対象検索 Lambda", "STS →（各 App の）DiscoveryReadRole", "同期", "対象検索 Lambda", "アカウントごとに 1 回",
      "App アカウントの認証構成情報を読むための一時クレデンシャルを取得する。",
      "sts:AssumeRole + ExternalId / sts.{region}.amazonaws.com（リージョナル STS）",
      "対象検索 Lambda -> STS : AssumeRole(DiscoveryReadRole, ExternalId)\nSTS --> 対象検索 Lambda : 一時クレデンシャル",
      "クレデンシャルの有効期限とキャッシュ方針を明記する"),
    P("巡回-04", "認証構成情報一覧取得", "認証構成情報一覧・版数取得", "巡回（1 時間毎）",
      "対象検索 Lambda", "認証構成情報連携バケット（App アカウント）", "同期", "対象検索 Lambda", "アカウントごとに 1 回",
      "連携バケットの {appId}/ を列挙し、各ファイルの版数（VersionId）を取得する（本文は取得しない）。",
      "s3:ListBucket / s3:ListBucketVersions / s3.{region}.amazonaws.com",
      "対象検索 Lambda -> 連携バケット : List（{appId}/ プレフィックス）\n連携バケット --> 対象検索 Lambda : キー一覧 + VersionId",
      "ページング処理と、monitoring.yaml が無いプレフィックスの扱いを明記する"),
    P("巡回-05", "前回確認状態取得", "前回確認状態取得", "巡回（1 時間毎）",
      "対象検索 Lambda", "認証構成情報配置バケット（registry/）", "同期", "対象検索 Lambda", "アプリごとに 1 回",
      "前回巡回時に確認した版数（lastArtifactVersions）などの状態を台帳から読み取る。",
      "s3:GetObject（同一アカウント）/ s3.{region}.amazonaws.com",
      "対象検索 Lambda -> 配置バケット : GetObject(registry/{appId}/{env}.json)\n配置バケット --> 対象検索 Lambda : 台帳 JSON（無ければ新規扱い）",
      "台帳が存在しない場合（初回）の扱いを明記する"),
    P("巡回-06", "認証構成情報比較", "認証構成情報比較", "巡回（1 時間毎）",
      "対象検索 Lambda（内部）", "—", "内部", "対象検索 Lambda", "アプリごとに 1 回",
      "連携バケットの版数と台帳の記録値を比較し、認証実装確認の要否を判定する。",
      "—（AWS 呼び出しなし）",
      "対象検索 Lambda : VersionId ↔ lastArtifactVersions を比較\n判定結果 = 変更あり / 変更なし / 新規",
      "【重要】比較は版数（メタデータ）で行い、内容ハッシュ比較にしない（17 §17.2.1 差分判定の 3 原則）"),
    P("巡回-07", "認証構成情報取得", "認証構成情報取得", "巡回（1 時間毎）",
      "対象検索 Lambda", "認証構成情報連携バケット（App アカウント）", "同期", "対象検索 Lambda", "変更のあったアプリのみ",
      "変更が検知されたアプリの認証構成情報（monitoring.yaml / openapi.yaml / deploy-info.json）を取得する。",
      "s3:GetObject / s3:GetObjectVersion / s3.{region}.amazonaws.com",
      "対象検索 Lambda -> 連携バケット : GetObject(monitoring.yaml, openapi.yaml)\n連携バケット --> 対象検索 Lambda : ファイル本体",
      "サイズ上限・文字コード・取得失敗時の扱いを明記する"),
    P("巡回-08", "認証構成情報検証", "認証構成情報検証", "巡回（1 時間毎）",
      "対象検索 Lambda（内部）", "—", "内部", "対象検索 Lambda", "取得ごとに 1 回",
      "monitoring.yaml のスキーマ検証と、appId とプレフィックスの一致検証を行う。",
      "—（AWS 呼び出しなし）",
      "対象検索 Lambda : YAML パース -> JSON Schema 検証 -> appId 一致検証\nNG の場合は 巡回-12 構成情報不備通知へ",
      "不備の分類（取り込み拒否 / 既定値で継続）を項目ごとに定義する（17 §17.3 の表）"),
    P("巡回-09", "認証構成情報登録", "認証構成情報登録", "巡回（1 時間毎）",
      "対象検索 Lambda", "認証構成情報配置バケット（registry/）", "同期", "対象検索 Lambda", "変更のあったアプリのみ",
      "台帳へ設定値を同期し、確認状態を更新する。中央管理項目（通知先・監視有効フラグ）は上書きしない。",
      "s3:PutObject（ETag 条件付き PUT, If-Match）/ s3.{region}.amazonaws.com",
      "対象検索 Lambda -> 配置バケット : PutObject（If-Match: 読取時 ETag）\n412 の場合は再読取してリトライ",
      "alertRouting / enabled を上書きしないマージ規則と、412 競合時のリトライ回数を明記する"),
    P("巡回-10", "API仕様登録", "API 仕様登録", "巡回（1 時間毎）",
      "対象検索 Lambda", "認証構成情報配置バケット（openapi/）", "同期", "対象検索 Lambda", "変更のあったアプリのみ",
      "取得した API 仕様（openapi.yaml）を中央の仕様保管領域へ複写する。",
      "s3:PutObject / s3.{region}.amazonaws.com",
      "対象検索 Lambda -> 配置バケット : PutObject(openapi/{accountId}/{appId}/openapi.yaml)",
      "キー導出規則と上書き方針（Versioning による履歴保全）を明記する"),
    P("巡回-11", "認証実装確認依頼", "認証実装確認依頼", "巡回（1 時間毎）",
      "対象検索 Lambda", "認証実装チェック Lambda", "非同期", "対象検索 Lambda", "変更のあったアプリごと",
      "変更が確定したアプリを対象に認証実装の確認を依頼する（自動差分検査＝モード1）。",
      "lambda:InvokeFunction（InvocationType=Event）/ lambda.{region}.amazonaws.com",
      "対象検索 Lambda -> 認証実装チェック Lambda : Invoke(Event, {mode:'delta', appId, env})\n※ 依頼成功後に 巡回-09 の版数を確定更新",
      "非同期リトライ（2 回）と DLQ の設定、依頼失敗時に台帳を更新しないこと（at-least-once）を明記する"),
    P("巡回-12", "構成情報不備通知", "構成情報不備通知", "巡回（1 時間毎）",
      "対象検索 Lambda", "SNS（P2 Platform）", "同期", "対象検索 Lambda", "不備検出時",
      "認証構成情報の不備（appId 不一致・必須項目欠落・認証方式の値が不正など）を通知する。",
      "sns:Publish / sns.{region}.amazonaws.com",
      "対象検索 Lambda -> SNS(P2) : Publish（不備種別・appId・該当項目）",
      "不備種別ごとの文面と、毎巡回で重複通知しない抑制方式を定義する"),
    P("巡回-13", "監視対象消滅検知", "監視対象消滅・鮮度低下検知", "巡回（1 時間毎）",
      "対象検索 Lambda", "配置バケット（registry/）+ SNS（P2）", "同期", "対象検索 Lambda", "巡回ごとに 1 回",
      "認証構成情報の消滅（アプリ廃止の可能性）と、長期間更新されていない状態（鮮度低下）を検知する。",
      "s3:PutObject（enabled=false）/ sns:Publish",
      "対象検索 Lambda : 台帳あり かつ 構成情報なし -> enabled=false + 棚卸しアラート\n対象検索 Lambda : 最終更新が閾値超 -> 鮮度低下アラート",
      "鮮度低下の閾値（仮 90 日、M-Q-17-3）と、一時的な取得失敗との区別を定義する"),
    P("巡回-14", "巡回結果メトリクス送信", "巡回結果メトリクス送信", "巡回（1 時間毎）",
      "対象検索 Lambda", "CloudWatch", "同期", "対象検索 Lambda", "巡回ごとに 1 回",
      "巡回の成功・失敗アカウント数などを、監視機構自身の稼働監視用メトリクスとして送信する。",
      "cloudwatch:PutMetricData / monitoring.{region}.amazonaws.com",
      "対象検索 Lambda -> CloudWatch : PutMetricData(DiscoveryLastSuccess, DiscoveryAccountErrors)",
      "メトリクス名・ディメンション・欠損時の扱い（MM-1 は 2h 欠損で発報）を明記する"),

    # ---------------- 全量確認
    P("全量-01", "全量確認処理開始（定期）", "全量確認処理開始（定期）", "全量（日次）",
      "EventBridge Scheduler（日次）", "認証実装チェック Lambda", "非同期", "EventBridge Scheduler", "日次",
      "認証構成情報の変化に関係なく全アプリを確認するため、全量確認を定期起動する。",
      "Scheduler 実行ロール / lambda:InvokeFunction",
      "EventBridge Scheduler -> 認証実装チェック Lambda : Invoke(Event, {mode:'full'})",
      "実行時刻帯（M-Q-18-3）と、巡回（巡回-01）と時間帯が重ならない配慮を明記する"),
    P("全量-02", "全量確認処理開始（手動）", "全量確認処理開始（手動）", "全量（手動・随時）",
      "運用者（CLI / コンソール）", "認証実装チェック Lambda", "非同期", "運用者", "随時（監査前・障害後など）",
      "運用者の判断で全量確認を実行する。実装は定期起動と同一で、起動元が人である点だけが異なる。",
      "lambda:InvokeFunction（実行者の IAM）",
      "運用者 -> 認証実装チェック Lambda : Invoke(Event, {mode:'full'})\n※ 特定アプリのみ: {mode:'full', appId, env}",
      "実行権限を持つ者の範囲（共通基盤チームのみか、アプリチームも可か。M-Q-18-3）を確定する"),
    P("全量-03", "監視対象一覧取得", "監視対象一覧取得", "全量（日次・手動）",
      "認証実装チェック Lambda", "認証構成情報配置バケット（registry/）", "同期", "認証実装チェック Lambda", "全量確認ごとに 1 回",
      "台帳を全件読み出し、監視有効な対象アプリの一覧を得る。",
      "s3:ListBucket / s3:GetObject",
      "認証実装チェック Lambda -> 配置バケット : List(registry/) -> GetObject（各件）\n配置バケット --> 認証実装チェック Lambda : 台帳 JSON 群",
      "enabled=false のレコードを除外すること、List のページングを明記する"),
    P("全量-04", "アプリ単位確認依頼", "アプリ単位確認依頼（fan-out）", "全量（日次・手動）",
      "認証実装チェック Lambda", "認証実装チェック Lambda（自身）", "非同期", "認証実装チェック Lambda", "対象アプリ数分",
      "全量確認を「1 実行 = 1 アプリ」に分割し、Lambda の実行時間上限に構造的に当たらないようにする。",
      "lambda:InvokeFunction（自身）/ lambda.{region}.amazonaws.com",
      "認証実装チェック Lambda(mode=full) -> 認証実装チェック Lambda(1 アプリ分) : アプリ数分 Invoke(Event)",
      "同時実行数の上限・スロットリング時の扱いを明記する"),

    # ---------------- 認証実装確認（1 アプリ・巡回/全量 共通）
    P("確認-01", "認証構成情報参照", "認証構成情報参照", "共通（巡回・全量とも）",
      "認証実装チェック Lambda", "認証構成情報配置バケット（registry/）", "同期", "認証実装チェック Lambda", "アプリごとに 1 回",
      "確認対象アプリの設定値（検査先 URL・認証方式・トークン設定）を台帳から取得する。",
      "s3:GetObject",
      "認証実装チェック Lambda -> 配置バケット : GetObject(registry/{appId}/{env}.json)\n配置バケット --> 認証実装チェック Lambda : 台帳 JSON",
      "台帳が取得できない場合（削除・権限不足）の扱いを明記する"),
    P("確認-02", "API仕様取得", "API 仕様取得", "共通（巡回・全量とも）",
      "認証実装チェック Lambda", "認証構成情報配置バケット（openapi/）", "同期", "認証実装チェック Lambda", "アプリごとに 1 回",
      "確認対象の endpoint 一覧と公開明示（MON-1）を取得する。",
      "s3:GetObject",
      "認証実装チェック Lambda -> 配置バケット : GetObject(openApiS3Key)\n配置バケット --> 認証実装チェック Lambda : API 仕様",
      "API 仕様が存在しない場合（モノリスの endpoint 列挙方式）の分岐を明記する"),
    P("確認-03", "正常系確認用トークン取得", "正常系確認用トークン取得", "共通（巡回・全量とも）",
      "認証実装チェック Lambda", "Secrets Manager → 認証基盤 /token", "同期", "認証実装チェック Lambda", "確認ごとに 1 回",
      "正常系アクセス確認で使う短命トークンを取得する。",
      "secretsmanager:GetSecretValue / 認証基盤の公開 /token（インターネット経由・OAuth client_credentials）",
      "認証実装チェック Lambda -> Secrets Manager : GetSecretValue\n認証実装チェック Lambda -> 認証基盤 /token : client_credentials\n認証基盤 --> 認証実装チェック Lambda : access_token（短命）",
      "トークンのキャッシュ有無・失効時の再取得・ログへのマスク（トークンを出力しない）を明記する"),
    P("確認-04", "未認証アクセス確認", "未認証アクセス確認", "共通（巡回・全量とも）",
      "認証実装チェック Lambda", "CloudFront → WAF → API GW / ALB", "同期", "認証実装チェック Lambda", "endpoint ごとに 1 回",
      "認証情報なしでリクエストし、正しく拒否されるか（401/403、Cookie 系は 302）を確認する。2xx なら認証実装漏れ。",
      "認証不要（Public 経路）/ HTTPS 443 / X-Auth-Probe ヘッダ付与（WAF 誤検知回避）",
      "認証実装チェック Lambda -> CloudFront : GET（認証ヘッダなし, X-Auth-Probe）\nCloudFront -> API GW : Origin Protection 付与\nAPI GW --> 認証実装チェック Lambda : ステータスコード",
      "公開明示（x-synthetics-skip-auth-check）付き endpoint の扱い、タイムアウト値、endpoint 単位の継続（1 件失敗で打ち切らない）を明記する"),
    P("確認-05", "正常系アクセス確認", "正常系アクセス確認", "共通（巡回・全量とも）",
      "認証実装チェック Lambda", "CloudFront → WAF → API GW / ALB", "同期", "認証実装チェック Lambda", "endpoint ごとに 1 回",
      "有効なトークン付きでリクエストし、200 が返ることで API 稼働と確認処理自体の健全性を確かめる。",
      "Bearer（確認-03 のトークン）/ HTTPS 443 / X-Auth-Probe ヘッダ付与",
      "認証実装チェック Lambda -> CloudFront : GET（Authorization: Bearer …, X-Auth-Probe）\nAPI GW --> 認証実装チェック Lambda : ステータスコード",
      "参照系のみ実行すること（更新系を叩かない）、対象 endpoint の選定規則を明記する"),
    P("確認-06", "確認結果判定", "確認結果判定（4×4）", "共通（巡回・全量とも）",
      "認証実装チェック Lambda（内部）", "—", "内部", "認証実装チェック Lambda", "endpoint ごとに 1 回",
      "未認証アクセス確認と正常系アクセス確認の結果の組み合わせから、重要度（CRITICAL / WARN / INFO / OK）を判定する。",
      "—（AWS 呼び出しなし）",
      "認証実装チェック Lambda : (未認証結果, 正常系結果) -> 4×4 真偽値表 -> 重要度決定\nWAF 起因の 403 は WARN（構成）に分類",
      "4×4 の全組み合わせと重要度の対応表を貼る（code-samples/README §2 が正）"),
    P("確認-07", "確認結果メトリクス送信", "確認結果メトリクス送信", "共通（巡回・全量とも）",
      "認証実装チェック Lambda", "CloudWatch", "同期", "認証実装チェック Lambda", "確認ごとに 1 回",
      "確認結果をメトリクス化し、保険系アラーム（AuthCheckCritical > 0）の入力とする。",
      "cloudwatch:PutMetricData / monitoring.{region}.amazonaws.com",
      "認証実装チェック Lambda -> CloudWatch : PutMetricData(AuthCheckCritical ほか, ディメンション=appId/env)",
      "ディメンション設計（アプリ数比例でメトリクス課金が増える点に注意）を明記する"),
    P("確認-08", "検知結果通知依頼", "検知結果通知依頼", "共通（巡回・全量とも）",
      "認証実装チェック Lambda", "アラート検知 Lambda", "非同期", "認証実装チェック Lambda", "重要度≠OK 時",
      "判定済みの検知結果を、通知の振り分けを行うアラート検知 Lambda へ引き渡す。",
      "lambda:InvokeFunction（InvocationType=Event）",
      "認証実装チェック Lambda -> アラート検知 Lambda : Invoke(Event, 4×4 判定済みイベント)",
      "イベント形式（README §2.6）と、配列でのバッチ送付の可否を明記する"),

    # ---------------- アラート通知
    P("通知-01", "通知先解決", "通知先解決", "共通（検知時）",
      "アラート検知 Lambda", "認証構成情報配置バケット（registry/）", "同期", "アラート検知 Lambda", "イベントごとに 1 回",
      "台帳の通知先設定から送信先を解決する。未設定時は全社デフォルトを使う。",
      "s3:GetObject",
      "アラート検知 Lambda -> 配置バケット : GetObject（alertRouting 参照）\n未設定 -> 全社デフォルト ARN",
      "2 段解決（アプリ個別 → 全社デフォルト）の順序と、未解決時に throw する仕様を明記する"),
    P("通知-02", "重要度別通知送信", "重要度別通知送信", "共通（検知時）",
      "アラート検知 Lambda", "SNS（P1 Security / P2 Platform / P3 App）", "同期", "アラート検知 Lambda", "イベントごとに 1 回",
      "重要度に応じた宛先へ通知を送信する。",
      "sns:Publish / sns.{region}.amazonaws.com",
      "アラート検知 Lambda -> SNS(P1|P2|P3) : Publish（件名・本文・appId・endpoint・判定根拠）",
      "通知本文のテンプレートと、1 件でも失敗したら throw（DLQ 発火）する仕様を明記する"),
    P("通知-03", "メトリクス閾値通知", "メトリクス閾値通知（保険系）", "共通（閾値超過時）",
      "CloudWatch Alarm", "SNS", "非同期", "CloudWatch", "閾値超過時",
      "アラート検知 Lambda の経路とは独立に、メトリクス閾値からも発報する（発報 2 系統の保険側）。",
      "CloudWatch Alarm → SNS（アラームアクション）",
      "CloudWatch Alarm(AuthCheckCritical > 0) -> SNS : 通知",
      "即時系（アラート検知 Lambda）と保険系の重複通知の扱いを明記する"),

    # ---------------- 運用・異常系
    P("運用-01", "監視機構稼働監視通知", "監視機構稼働監視通知（MM-1〜5）", "随時（異常時）",
      "CloudWatch Alarm", "SNS（P2 Platform）", "非同期", "CloudWatch", "閾値超過時",
      "監視機構そのものの停止・失敗を検知して発報する（監視の空白＝検知の空白を防ぐ）。",
      "CloudWatch Alarm → SNS",
      "Alarm(DiscoveryLastSuccess 2h 欠損 / Lambda Errors / DLQ 滞留) -> SNS(P2)",
      "MM-1〜5 の各アラーム定義（対象メトリクス・閾値・評価期間）を一覧化する"),
    P("運用-02", "処理失敗退避・再処理", "処理失敗退避・再処理（DLQ）", "随時（異常時）",
      "各 Lambda（非同期実行の失敗）", "SQS DLQ → 運用者", "非同期", "Lambda / 運用者", "失敗時",
      "非同期呼び出しがリトライ後も失敗した場合に退避し、後から再処理・原因調査できるようにする。",
      "Lambda 非同期呼び出しの DLQ 設定 / sqs:ReceiveMessage・DeleteMessage（運用者）",
      "Lambda(失敗) -> 自動リトライ(2 回) -> SQS DLQ\n運用者 -> DLQ : 内容確認 -> 再実行",
      "DLQ の保持期間・再処理手順（Runbook 化）・滞留アラーム（MM-4/5）を明記する"),
    P("運用-03", "監視設定手動更新", "監視設定手動更新", "随時（運用操作）",
      "運用者", "認証構成情報配置バケット（registry/）", "同期", "運用者", "随時",
      "監視の有効・無効の切替や通知先の設定など、中央管理項目を運用者が更新する。",
      "s3:GetObject / s3:PutObject（ETag 条件付き）",
      "運用者 -> 配置バケット : GetObject -> 編集 -> PutObject（If-Match）\n巡回と競合した場合は 412 -> 再取得",
      "巡回（巡回-09）との競合手順、変更履歴の追跡（Versioning）、承認フローの要否を明記する"),

    # ---------------- アプリ接点
    P("連携-01", "認証構成情報配置", "認証構成情報配置（アプリ側）", "随時（デプロイのたび）",
      "ベンダー CI（デプロイパイプライン最終段）", "認証構成情報連携バケット（App アカウント）", "同期", "ベンダー CI", "デプロイのたび",
      "デプロイ成功後に認証構成情報を配置する。本監視の入口であり、アプリ（ベンダー）側の責務。",
      "ArtifactUploadRole-{appId} を Assume / s3:PutObject（{appId}/* 限定）/ s3.{region}.amazonaws.com",
      "ベンダー CI -> STS : AssumeRole(ArtifactUploadRole-{appId})\nベンダー CI -> 連携バケット : PutObject(monitoring.yaml, openapi.yaml, deploy-info.json)",
      "デプロイ成功後に実行すること（順序逆転の禁止）、配置漏れは原則アプリ責任（M-Q-17-7）である旨を明記する"),
]
